power <- fread("household_power_consumption.txt")
power$Date <- as.Date(power$Date, "%d/%m/%Y")
power <- transform(power, Date = as.character(Date))
power<-transform(power, Date = substring(Date, 1, 10), time = substring(Date, 10, 17))
subpower<-subset(power, as.Date(Date) >= '2007-02-01' & as.Date(Date) <= '2007-02-02')
rm(power)
subpower<-transform(subpower, datetime = chron(Date, Time, format=c("y-m-d","h:m:s")))
png(filename="plot2.png", width=480, height=480, bg = "transparent")
plot(subpower$datetime,subpower$Global_active_power,typ='l',ylab="Global Active Power (kilowatts)",xlab="",xaxt="n")
axis(1, labels=c("Thu","Fri","Sat"), at=c('13545.0','13546.0','13547.0'))
dev.off()
