power <- fread("household_power_consumption.txt")
power$Date <- as.Date(power$Date, "%d/%m/%Y")
power <- transform(power, Date = as.character(Date))
power<-transform(power, Date = substring(Date, 1, 10), time = substring(Date, 10, 17))
subpower<-subset(power, as.Date(Date) >= '2007-02-01' & as.Date(Date) <= '2007-02-02')
subpower<-transform(subpower, datetime = chron(Date, Time, format=c("y-m-d","h:m:s")))
rm(power)
png(filename="plot4.png", width=480, height=480, bg = "transparent")
par(mfrow=c(2,2))
plot(subpower$datetime,subpower$Global_active_power,typ='l',ylab="Global Active Power",xlab="",xaxt="n")
axis(1, labels=c("Thu","Fri","Sat"), at=c('13545.0','13546.0','13547.0'))
plot(subpower$datetime,subpower$Voltage,typ='l',ylab="Voltage",xlab="datetime",xaxt="n")
axis(1, labels=c("Thu","Fri","Sat"), at=c('13545.0','13546.0','13547.0'))
plot(subpower$datetime, subpower$Sub_metering_1, typ='l',ylab="Energy sub metering",xlab="",xaxt="n")
axis(1, labels=c("Thu","Fri","Sat"), at=c('13545.0','13546.0','13547.0'))
lines(subpower$datetime, subpower$Sub_metering_3, col="blue")
lines(subpower$datetime, subpower$Sub_metering_2, col="red")
legend('topright',c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.8,lty=c(1,1,1), bty='n',lwd=c(1,1,1),col=c("black","red","blue"))
plot(subpower$datetime,subpower$Global_reactive_power,typ='l',ylab="Global_reactive_power",xlab="datetime",xaxt="n")
axis(1, labels=c("Thu","Fri","Sat"), at=c('13545.0','13546.0','13547.0'))
dev.off()