power <- fread("household_power_consumption.txt")
power$Date <- as.Date(power$Date, "%d/%m/%Y")
power <- transform(power, Date = as.character(Date))
power<-transform(power, Date = substring(Date, 1, 10), time = substring(Date, 10, 17))
subpower<-subset(power, as.Date(Date) >= '2007-02-01' & as.Date(Date) <= '2007-02-02')
rm(power)
png(filename="plot1.png", width=480, height=480, bg = "transparent")
hist(as.numeric(subpower$Global_active_power), xlab="Global Active Power (kilowatts)", main="Global Active Power", col="red")
dev.off()
